#!/bin/bash
# Script by : jAvaNet


echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0m           AutoScriptVPS by  jAvaNet            "
echo -e "\e[0m                                                   "
echo -e "\e[0;96m            [1] รีบูตทุก 1 ชั่วโมง "
echo -e "\e[0;96m            [2] รีบูตทุก 2 ชั่วโมง "
echo -e "\e[0;96m            [3] รีบูตทุก  12 ชั่วโมง "
echo -e "\e[0;96m            [4] รีบูตทุกวัน "
echo -e "\e[0;96m            [5] รีบูตทุกสัปดาห์ "
echo -e "\e[0;96m            [6] รีบูตทุกเดือน "
echo -e "\e[0;96m            [7] ปิดใช้งานการรีบูตอัตโนมัติ  "
echo -e "\e[0;96m            [x] ออก "
echo -e "\e[0m                                                   "
read -p "               โปรดเลือก [1-7 or x] :  " Reboot_Sys
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
clear
case $Reboot_Sys in
		1)
		clear
		echo "10 * * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m           เปิดใช้งานการรีบูตทุก 1 ชั่วโมงแล้ว        "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		2)
		clear
		echo "10 */6 * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet           "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m          เปิดใช้งานการรีบูตทุก 2 ชั่วโมงแล้ว "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		3)
		clear
		echo "10 */12 * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m          เปิดใช้งานการรีบูตทุก 12 ชั่วโมงแล้ว       "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		4)
		clear
		echo "10 0 * * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m            เปิดการใช้งานการรีบูตทุกวัน               "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		5)
		clear
		echo "10 0 */7 * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m           เปิดการใช้งานรีบูตทุกสัปดาห์            "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		6)
		clear
		echo "10 0 1 * * root /usr/local/bin/reboot_sys" > /etc/cron.d/reboot_sys
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m           เปิดการใช้งานการรีบูตทุกเดือน           "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		7)
		clear
		rm -f /etc/cron.d/reboot_sys
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m                ปิดใช้งานการรีบูตอัตโนมัติ               "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		x)
		clear
		exit
		;;
	esac