#!/bin/bash
# Script by : jAvaNet 


echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
echo -e "\e[0m                                                   "
echo -e "\e[0;96m            [1] รีบูตตอนนี้"
echo -e "\e[0;96m            [2] กำหนดเวลารีบูต"
echo -e "\e[0;96m            [x] ออก"
echo -e "\e[0m                                                   "
read -p "             โปรดเลือก [1-3 or x] :  " Reboot
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
clear
case $Reboot in
		1)
		clear
		reboot
		exit
		;;
		2)
		clear
		reboot_sys_auto
		exit
		;;
		x)
		clear
		exit
		;;
	esac