#!/bin/bash
# Script by : Darknet 


echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;96m           AutoScriptVPS by  Darknet            "
echo -e "\e[0m                                                   "
echo -e "\e[0;96m            [1] SHOW ALL PORT"
echo -e "\e[0;96m            [2] EDIT PORT OPENSSH"
echo -e "\e[0;96m            [3] EDIT PORT DROPBEAR"
echo -e "\e[0;96m            [4] EDIT PORT STUNNEL"
echo -e "\e[0;96m            [5] EDIT PORT OPENVPN"
echo -e "\e[0;96m            [6] EDIT PORT SQUID"
echo -e "\e[0;96m            [x] LEAVE"
echo -e "\e[0m                                                   "
read -p "           please choose from  [1-6 or x] :  " Port
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
clear
case $Port in
			1)
			clear
			show_ports
			exit
			;;
			2)
			clear
			port-ssh
			exit
			;;
			3)
			clear
			port-dropbear
			exit
			;;
			4)
			clear
			port-stunnel
			exit
			;;
			5)
			clear
			port-ovpn
			exit
			;;
			6)
			clear
			port-squid
			exit
			;;
			x)
			clear
			exit
			;;
	esac
