#!/bin/bash
# Script by : jAvaNet 


echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
echo -e "\e[0m                                                   "
echo -e "\e[0;96m            [1] แสดงพอร์ตทั้งหมด"
echo -e "\e[0;96m            [2] แก้ไขพอร์ต OpenSSH"
echo -e "\e[0;96m            [3] แก้ไขพอร์ต Dropbear"
echo -e "\e[0;96m            [4] แก้ไขพอร์ต Stunnel"
echo -e "\e[0;96m            [5] แก้ไขพอร์ต OpenVPN"
echo -e "\e[0;96m            [6] แก้ไขพอร์ต Squid"
echo -e "\e[0;96m            [x] ออก"
echo -e "\e[0m                                                   "
read -p "            โปรดเลือกจาก  [1-6 or x] :  " Port
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
clear
case $Port in
			1)
			clear
			show_ports
			exit
			;;
			2)
			clear
			edit_openssh
			exit
			;;
			3)
			clear
			edit_dropbear
			exit
			;;
			4)
			clear
			edit_stunnel4
			exit
			;;
			5)
			clear
			edit_openvpn
			exit
			;;
			6)
			clear
			edit_squid3
			exit
			;;
			x)
			clear
			exit
			;;
	esac