#!/bin/bash
# Script by : jAvaNet 


rm -f /root/opensshport
rm -f /root/dropbearport
rm -f /root/stunnel4port
rm -f /root/openvpnport
rm -f /root/squidport
opensshport="$(netstat -ntlp | grep -i ssh | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
stunnel4port="$(netstat -nlpt | grep -i stunnel | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
openvpnport="$(netstat -nlpt | grep -i openvpn | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
squidport="$(cat /etc/squid3/squid.conf | grep -i http_port | awk '{print $2}')"
echo $opensshport > /root/opensshport
cat > /root/opensshport <<-END
$opensshport
END
echo $dropbearport > /root/dropbearport
cat > /root/dropbearport <<-END
$dropbearport
END
echo $stunnel4port > /root/stunnel4port
cat > /root/stunnel4port <<-END
$stunnel4port
END
echo $openvpnport > /root/openvpnport
cat > /root/openvpnport <<-END
$openvpnport
END
echo $squidport > /root/squidport
cat > /root/squidport <<-END
$squidport
END

cd
clear
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
echo -e "\e[0m                                                   "
echo -e "\e[0;96m                Dropbear  Ports                 "
echo -e "\e[0;96m                "$dropbearport
echo -e "\e[0m                                                   "
read -p "       คุณต้องการเปลี่ยนพอร์ตไหน? :  " Port
egrep "^$Port" /root/dropbearport >/dev/null
if [ $? -eq 0 ]; then
	read -p "            From Port $Port -> Port " Port_New
	if grep -Fxq $Port_New /root/opensshport; then
		echo -e "\e[0m                                                   "
		echo -e "\e[095m              OpenSSH Port Conflict              "
		echo -e "\e[095m              พอร์ตถูกใช้งานแล้ว              "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
	fi
	if grep -Fxq $Port_New /root/stunnel4port; then
		echo -e "\e[0m                                                   "
		echo -e "\e[095m              Stunnel4 Port Conflict              "
		echo -e "\e[095m              พอร์ตถูกใช้งานแล้ว              "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
	fi
	if grep -Fxq $Port_New /root/openvpnport; then
		echo -e "\e[0m                                                   "
		echo -e "\e[095m              Openvpn Port Conflict               "
		echo -e "\e[095m              พอร์ตถูกใช้งานแล้ว              "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
	fi
	if grep -Fxq $Port_New /root/squidport; then
		echo -e "\e[0m                                                   "
		echo -e "\e[095m               Squid3 Port Conflict               "
		echo -e "\e[095m              พอร์ตถูกใช้งานแล้ว              "
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
	fi
	Port_Change="s/$Port/$Port_New/g";
	sed -i $Port_Change /etc/default/dropbear

	service dropbear restart > /dev/null
	rm -f /root/dropbear
	dropbearport="$(netstat -nlpt | grep -i dropbear | grep -i 0.0.0.0 | awk '{print $4}' | cut -d: -f2)"
	clear
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]"
	echo -e "\e[0m                                                   "
	echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet            "
	echo -e "\e[0m                                                   "
	echo -e "\e[0;95m                  Dropbear  Ports                 "
	echo -e "\e[0;95m                  "$dropbearport
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"

else
	clear
	echo -e "\e[0m                                                   "
	echo -e "\e[095m                 พอร์ตไม่มีในระบบ                 "
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
fi

