#!/bin/bash
# Script by : jAvaNet

datenow=$(date +%s)
for user in $(awk -F: '{print $1}' /etc/passwd); do
expdate=$(chage -l $user|awk -F: '/Account expires/{print $2}')
echo $expdate|grep -q never && continue
echo -n "User \`$user' expires on $expdate ... "
expsec=$(date +%s --date="$expdate")
diff=$(echo $datenow - $expsec|bc -l)
echo $diff|grep -q ^\- && echo okay && continue
# got this far, account must have expired
userdel -r $user  &> /dev/null
done
clear
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;96m             AutoScriptVPS by  jAvaNet            "
echo -e "\e[0m                                                   "
echo -e "\e[0;95m              ลบบัญชีหมดอายุทั้งหมดแล้ว        "
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"

