#!/bin/bash
# Script by :jAvaNet


echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;96m              AutoScriptVPS by  jAvaNet           "
echo -e "\e[0m                                                   "
read -p "                      บัญชีที่ต้องการลบ :  " User
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
egrep "^$User" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
	userdel -f $User
	clear
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]"
	echo -e "\e[0m                                                   "
	echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet           "
	echo -e "\e[0m                                                   "
	echo -e "\e[0;95m             บัญชีถูกลบจากระบบแล้ว                   "
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
else
	clear
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]"
	echo -e "\e[0m                                                   "
	echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet           "
	echo -e "\e[0m                                                   "
	echo -e "\e[095m                ไม่มีบัญชีในระบบ                "
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
fi