#!/bin/bash
# Script by :Darknet


echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;96m              AutoScriptVPS by  Darknet           "
echo -e "\e[0m                                                   "
read -p "                      Account to delete :  " User
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
egrep "^$User" /etc/passwd >/dev/null
if [ $? -eq 0 ]; then
	userdel -f $User
	clear
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]"
	echo -e "\e[0m                                                   "
	echo -e "\e[0;96m           AutoScriptVPS by  Darknet           "
	echo -e "\e[0m                                                   "
	echo -e "\e[0;95m          The account has been deleted         "
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
else
	clear
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]"
	echo -e "\e[0m                                                   "
	echo -e "\e[0;96m           AutoScriptVPS by  Darknet           "
	echo -e "\e[0m                                                   "
	echo -e "\e[095m            No account in the system            "
	echo -e "\e[0m                                                   "
	echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
fi
