#!/bin/bash
#Script by : darknet

if [[ -e /etc/debian_version ]]; then
	OS=debian
	RCLOCAL='/etc/rc.local'
elif [[ -e /etc/centos-release || -e /etc/redhat-release ]]; then
	OS=centos
	RCLOCAL='/etc/rc.d/rc.local'
	chmod +x /etc/rc.d/rc.local
else
	echo "It looks like you are not running this installer on Debian, Ubuntu or Centos system"
	exit
fi
echo -e ""
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
echo -e ""
echo -e "\e[0;94m      { WELCOME TO DARKNET SCRIPT SSHVPN MENU }"
echo -e "\e[0;96m create    :  CREATE NEW USER SSH/OVPN"
echo -e "\e[0;96m member    :  SHOW USER LIST "
echo -e "\e[0;96m delete    :  DELETE USER "
echo -e "\e[0;96m delexp    :  DELETE EXP USER "
echo -e "\e[0;96m check     :  CHECK USER LOGIN "
echo -e "\e[0;96m autokill  :  AUTOKILL MULTI LOGIN "
echo -e "\e[0;96m banner    :  SETTING BANNER "
echo -e "\e[0;96m exit      :  EXIT SSHMENU "
echo -e "\e[0m                                                   "
read -p "      Please select your menu :  " menussh
echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
clear
case $menu in
		create)
		clear
		create
		exit
		;;
		member)
		clear
		list-user
		exit
		;;
		delete)
		clear
		del-user
		exit
		;;
		delexp)
		clear
		del-exp
		exit
		;;
		check)
		clear
		show-login
		exit
		;;
		autokill)
		clear
		multi-login
		exit
		;;
		banner)
		clear
		nano /etc/banner
		exit
		;;
		exit)
		clear
		menu
		;;
	esac
