#!/bin/bash
# Script by : jAvaNet

echo -e "\e[0m                                                   "
echo -e "\e[037m[*][*][*]======================================[*][*][*]"
echo -e "\e[0m                                                   "
echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet           "
echo -e "\e[0m                                                   "
echo -e "\e[0;96m    [1] ลบบัญชีอัตโนมัติหลังจากห้านาที "
echo -e "\e[0;96m    [2] ลบบัญชีอัตโนมัตหลังจากสิบนาที "
echo -e "\e[0;96m    [3] ลบบัญชีอัตโนมัตหลังจากสามสิบนาที "
echo -e "\e[0;96m    [4] ปิดการใช้งานการลบบัญชีอัตโนมัติ "
echo -e "\e[0;96m    [x] ออก "
echo -e "\e[0m                                                   "
read -p "           โปรดเลือก [1-5 or x] :  " AutoKill
echo -e "\e[0m                                                   "
case $AutoKill in
		1)
		read -p "            อนุญาตใช้งานหลายบัญชี        :  " -e -i 1 MultiLogin
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		clear
		echo "*/5 * * * *  root /usr/bin/set_multilogin_autokill_lib $MultiLogin" > /etc/cron.d/set_multilogin_autokill_lib
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet           "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m      อนุญาตใช้งานหลายบัญชี : "$MultiLogin
		echo -e "\e[0;95m      ลบบัญชีอัตโนมัติหลังจาก    : 5 Minutes"
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		2)
		read -p "            อนุญาตใช้งานหลายบัญชี        :  " -e -i 1 MultiLogin
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"s
		sleep 4
		clear
		echo "*/15 * * * *  root /usr/bin/set_multilogin_autokill_lib $MultiLogin" > /etc/cron.d/set_multilogin_autokill_lib
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet           "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m      อนุญาตใช้งานหลายบัญชี : "$MultiLogin
		echo -e "\e[0;95m      ลบบัญชีอัตโนมัติหลังจาก     : 15 Minutes"
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		3)
		read -p "             อนุญาตใช้งานหลายบัญชี        :  " -e -i 1 MultiLogin
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		sleep 4
		clear
		echo "*/30 * * * *  root /usr/bin/set_multilogin_autokill_lib $MultiLogin" > /etc/cron.d/set_multilogin_autokill_lib
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet           "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m     อนุญาตใช้งานหลายบัญชี : "$MultiLogin
		echo -e "\e[0;95m     ลบบัญชีอัตโนมัติหลังจาก     : 30 Minutes"
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		4)
		clear
		rm -f /etc/cron.d/set_multilogin_autokill_lib
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]"
		echo -e "\e[0m                                                   "
		echo -e "\e[0;96m           AutoScriptVPS by  jAvaNet           "
		echo -e "\e[0m                                                   "
		echo -e "\e[0;95m            ปิดการใช้งานลบบัญชีอัตโนมัติ"
		echo -e "\e[0m                                                   "
		echo -e "\e[037m[*][*][*]======================================[*][*][*]\e[0m"
		exit
		;;
		x)
		clear
		exit
		;;
	esac